"""Check that every ratio published in prose matches the measured artifacts.

Phase 4 shipped "6.9x better than bigram" when the true figure was 7.65x. Nothing
was wrong with the measurement — the ratio had been worked out by hand during a
progress update, when validation perplexity was still 6.097, and carried into the
final prose without being recomputed. A stale denominator, invisible because
nothing checked prose against data (ADR-020).

This closes that hole. Every "Nx better" claim in the docs is matched against
`results/perplexity_floors.json`, which is generated by measurement.

**Every** "Nx better" in the docs is checked, with no exemptions. An earlier
version skipped matches inside double quotes so ADRs could quote the figures they
were correcting — but pairing quotes across a whole file is unreliable, and it
silently skipped three real claims in ADR-017 while reporting success. A checker
that quietly ignores claims is worse than no checker. Historical or incorrect
figures are therefore phrased without the "Nx better" pattern ("a ratio of 6.9")
so they are visibly not claims.

    python -m src.verify_docs
"""

from __future__ import annotations

import json
import re
import sys

from config import REPO_ROOT

DOCS = ("README.md", "ADR.md")
RATIO = re.compile(r"([\d,]+(?:\.\d+)?)\s*[x×]\s*better", re.IGNORECASE)
REL_TOL = 0.005  # 0.5%: allows sane rounding, catches a wrong denominator


def published_ratios(text: str) -> list[tuple[int, float]]:
    """Every ratio claim in the prose. No exclusions, by design."""
    return [
        (text[: m.start()].count("\n") + 1, float(m.group(1).replace(",", "")))
        for m in RATIO.finditer(text)
    ]


def main() -> int:
    path = REPO_ROOT / "results" / "perplexity_floors.json"
    if not path.exists():
        raise SystemExit("run `python -m src.baselines --with-model checkpoints/base.pt` first.")
    floors = json.loads(path.read_text(encoding="utf-8"))
    if "model" not in floors:
        raise SystemExit("perplexity_floors.json has no model entry - rerun with --with-model.")

    model_ppl = floors["model"]["perplexity"]
    measured = {n: v["perplexity"] / model_ppl for n, v in floors["baselines"].items()}
    # The design ratio (threshold vs bigram floor) is a decision, not a result.
    allowed = dict(measured)
    allowed["threshold_design"] = floors["baselines"]["bigram"]["perplexity"] / \
        floors.get("threshold", 8.0)

    print(f"model perplexity (identical tokens) : {model_ppl}")
    for name, r in sorted(measured.items(), key=lambda kv: kv[1]):
        print(f"  vs {name:<9} {r:>12,.4f}x")
    print()

    failures = 0
    for doc in DOCS:
        text = (REPO_ROOT / doc).read_text(encoding="utf-8")
        for line, claim in published_ratios(text):
            hit = any(abs(claim - v) <= REL_TOL * max(v, 1.0) for v in allowed.values())
            if not hit:
                failures += 1
            print(f"  [{'ok  ' if hit else 'FAIL'}] {doc}:{line:<5} {claim:>12,.2f}x")

    print()
    if failures:
        print(f"{failures} published ratio(s) do not match the measured artifact.")
        return 1
    print("all published ratios match the measured artifact")
    return 0


if __name__ == "__main__":
    sys.exit(main())
